### ISSUE TITLE
[FEATURE] Add support for suffix 

### ISSUE THREAD

**Issue by menathan** [restechnica/semverbot#72]
Next to a `git.tags.prefix` config, also add a `git.tags.suffix` config option.

Example for `.semverbot.toml`:

```toml
[git.tags]
suffix = "-my-cool-suffix"
``` 

Expected result:

`<semver>-my-cool-suffix` e.g. `0.3.1-my-cool-suffix`
