### ISSUE TITLE
Inconsistent version prediction

### ISSUE THREAD

**Issue by emulanob** [restechnica/semverbot#76]
Hey there!

I spent quite a few hours today testing the git-commit mode. 
My goal was to determine the easisest way for my team to have "regular" minor version releases and keep the ability to bump the major version when needed by prefixing the commit message.

I ended up noticing inconsistent version predictions.

For example, given the following semver config:
```toml
mode = "git-commit"

[git]

[git.config]
email = "semverbot@github.com"
name = "semverbot"

[git.tags]
prefix = "v"

[semver]
patch = ["hotfix", "bugfix", "fix", "bug"]
minor = ["feature", "feat", "release"]
major = ["breaking", "major"]

[modes]

[modes.git-branch]
delimiters = "/"

[modes.git-commit]
delimiters = "[]/"
```

and the following commit message:
```
git commit -m "[breaking] [feature] [hotfix]" --amend
```

I got 3 different predictions in 3 tries.
<img width="793" alt="image" src="https://github.com/user-attachments/assets/a12657b6-565f-4db8-b5b8-26a969babf10">

So maybe when this gets fixed there could also be a way to enforce hierarchy in the matching? Which in my opinion should always go major --> minor --> patch.

Thanks!
